# add this configuration to your application's config.yml
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ATUserBundle\Entity\User